name: kong

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  kong:
    needs: update-cache
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: kong-cache
          path: ~/tmp/kong/cache

      - name: Install Deps
        run: npm install

      - name: Setup erlang SDK
        run: npm run kong -- setup erlang -v

      - name: Build Bridge Image
        run: npm run kong -- build erlang -v

      - name: Run Tests
        run: npm run kong -- test erlang -v -r
